const words = [
    "Accessory",
    "Agatha",
    "Alloy",
    "Amber",
    "Amethyst",
    "Aquamarine",
    "Artifact",
    "Astraea",
    "Auction",
    "Aurora",
    "Barn",
    "Bazaar",
    "Belt",
    "Bingo",
    "Bits",
    "Blaze",
    "Bonzo",
    "Catalyst",
    "Charm",
    "Chronomicon",
    "Chum",
    "Citrine",
    "Cloak",
    "Coin",
    "Crimson",
    "Cropie",
    "Derpy",
    "Diamond",
    "Diana",
    "Divan",
    "Dungeon",
    "Dwarven",
    "Ectoplasm",
    "Emerald",
    "Enderman",
    "Essence",
    "Farm",
    "Felthorn",
    "Fermento",
    "Fervor",
    "Forge",
    "Garden",
    "Gemstone",
    "Ghast",
    "Glacite",
    "Glossy",
    "Gloves",
    "Gold",
    "Goldor",
    "Golem",
    "Griffin",
    "Heirloom",
    "Hellfire",
    "Hex",
    "Hollow",
    "Hollows",
    "Hyperion",
    "Inferno",
    "Infusion",
    "Jade",
    "Jasper",
    "Jawbus",
    "Jerry",
    "Juju",
    "Kuudra",
    "Livid",
    "Maxor",
    "Medal",
    "Melon",
    "Minion",
    "Mithril",
    "Necklace",
    "Necron",
    "Nether",
    "Obsidian",
    "Onyx",
    "Opal",
    "Park",
    "Paul",
    "Peridot",
    "Pet",
    "Prismarine",
    "Reaper",
    "Recombobulator",
    "Reforge",
    "Relic",
    "Revenant",
    "Rift",
    "Rift-Ferret",
    "Ring",
    "Ritual-residue",
    "Ruby",
    "Rune",
    "Sack",
    "Sadan",
    "Sapphire",
    "Scarf",
    "Scatha",
    "Scorpius",
    "Scroll",
    "Scylla",
    "Slayer",
    "Sludge",
    "Spider",
    "Squash",
    "Squid",
    "Storm",
    "Sulphur",
    "Sven",
    "Talisman",
    "Tarantula",
    "Terminator",
    "Terror",
    "Thorn",
    "Thunder",
    "Topaz",
    "Travel-Scroll",
    "Valkyrie",
    "Vanquisher",
    "Voidgloom",
    "Warden",
    "Wither",
    "Yeti",
    "Zealot",
    "Shy-Crux",
    "Freshly-Minted-Coins",
    "Frozen-Blaze",
    "Cutlass",
    "Magma-Lord",
    "Kelvin-Inverter",
    "X",
    "Gunthesizer-Lichen",
    "Sorrow",
    "Figstone-Splitter",
    "Figstone",
    "Infernal",
    "Hot",
    "Fiery",
    "Burning",
    "Titanium-Tesseract",
    "Shortbow",
    "Spirit-Sceptre",
    "Ghostly-boots",
    "Implosion-Belt",
    "Frog",
    "Master-Star",
    "Everburning-Flame",
    "Mosquito-bow",
    "Deathripper-Dagger",
    "Last-Breath",
    "Bacte",
    "Bacte-Fragment",
    "Spring-Boots",
    "Mangrove",
    "Diamantes-Handle",
    "Icy-sinker",
    "Plasma-Nucleus",
    "Reaper-Scythe",
    "Jade-Dragon",
    "Yog",
    "Steak-Stake",
    "Golden-Gift",
    "Soulflow",
    "Splatter-Crux",
    "Crux",
    "Cleaver",
    "Gauntlet",
    "Jaderald",
    "Nether-Star",
    "Spruce-Axe",
    "Pooch-Sword",
    "Abiphone",
    "Pyrochaos-Dagger",
    "FTX-3070",
    "Minemort",
    "Strategybob",
    "Abyssal",
    "Arack",
    "Travel-Scroll",
    "Autpet",
    "Kraken",
    "Bouquet-of-Lies",
    "Blood-God-Crest",
    "Boss-Corleone",
    "Bonemerang",
    "Ankylosaurus",
    "Archfiend-Dice",
    "Artifact-of-Control",
    "Biohazard",
    "Cactus-Knife",
    "Control-switch",
    "Ember-rod",
    "Egglocator",
    "Century-Cake",
    "Figmail",
    "Finwave-cloak",
    "Frozen-Scythe",
    "Ghoul-Buster",
    "Gemstone-Gauntlet",
    "Flaming-Flay",
    "Giant-Fishing-Rod",
    "InfiniVacuum",
    "Magma-Urchin",
    "Melodys-Hair",
    "Kat-Flower",
    "Kat",
    "Elizabeth",
    "Null-blade",
    "Pickonimbus",
    "Scarfs-Studies",
    "Sinseeker-Scythe",
    "Skeletor",
    "Soulflow",
    "Soul-Whip",
    "Spirit-Bone",
    "Spirit-Mask",
    "Stock-of-Stonks",
    "Liz",
    "Diaz",
    "Yeti-sword",
    "Undead-Catalyst",
    "Vampire-Mask",
    "Vorpal-Katana",
    "Wriggling-Larva",
    "Atomsplit-Katana",
    "Jyrre",
    "Rubiclex",
];

function getRandomWord(length = undefined) {
    length = undefined;
    if (length !== undefined) {
        const filteredWords = words.filter((word) => word.length == length);

        if (filteredWords.length === 0) {
            // eslint-disable-next-line no-throw-literal
            throw `No words found with the ${length} characters.`;
        }

        return filteredWords[Math.floor(Math.random() * filteredWords.length)];
    } else {
        return words[Math.floor(Math.random() * words.length)];
    }
}

function scrambleWord(word) {
    const chars = word.split('');

    for (let i = chars.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [chars[i], chars[j]] = [chars[j], chars[i]];
    }

    return word === chars.join('') ? scrambleWord(word) : chars.join('');
}

module.exports = { getRandomWord, scrambleWord };
