// API/constants/garden.js
// Contains all garden-related constants

const CROP_IDS_MAP = {
    WHEAT: 'WHEAT',
    CARROT: 'CARROT_ITEM',
    POTATO: 'POTATO_ITEM',
    PUMPKIN: 'PUMPKIN',
    MELON: 'MELON',
    MELON_SLICE: 'MELON',
    NETHER_WART: 'NETHER_STALK',
    SUGAR_CANE: 'SUGAR_CANE',
    CACTUS: 'CACTUS',
    MUSHROOM: 'MUSHROOM_COLLECTION',
    COCOA_BEANS: 'INK_SACK:3',
    SUNFLOWER: 'DOUBLE_PLANT',
    SUN_FLOWER: 'DOUBLE_PLANT',
    MOONFLOWER: 'MOONFLOWER',
    WILD_ROSE: 'WILD_ROSE',
    ROSE: 'WILD_ROSE'
};

const CROP_MILESTONE_CAPS = {
    WHEAT: 20200000,
    SUNFLOWER: 20200000,
    SUN_FLOWER: 20200000,
    MOONFLOWER: 20200000,
    PUMPKIN: 20200000,
    MUSHROOM: 20200000,
    CARROT: 66200000,
    POTATO: 66200000,
    SUGAR_CANE: 40400000,
    CACTUS: 40400000,
    WILD_ROSE: 40400000,
    ROSE: 40400000,
    COCOA_BEANS: 60900000,
    NETHER_WART: 60900000,
    MELON: 101100000,
    MELON_SLICE: 101100000
};

const PERSONAL_BEST_FF_AMOUNTS = {
    WHEAT: 1000,
    CARROT_ITEM: 3000,
    POTATO_ITEM: 3000,
    PUMPKIN: 1000,
    MELON: 5000,
    MUSHROOM_COLLECTION: 1000,
    CACTUS: 2000,
    SUGAR_CANE: 2000,
    NETHER_STALK: 3000,
    'INK_SACK:3': 3000
};

const VISITOR_RARITY_MAP = {
    ADVENTURER: 'UNCOMMON', ALCHEMIST: 'UNCOMMON', ANDREW: 'UNCOMMON',
    ANITA: 'UNCOMMON', ARTHUR: 'UNCOMMON', BANKER_BROADJAW: 'UNCOMMON',
    DUKE: 'UNCOMMON', DUSK: 'UNCOMMON', EMISSARY_CARLTON: 'UNCOMMON',
    EMISSARY_CEANNA: 'UNCOMMON', EMISSARY_FRAISER: 'UNCOMMON', EMISSARY_WILSON: 'UNCOMMON',
    FARMER_JON: 'UNCOMMON', FARMHAND: 'UNCOMMON', FEAR_MONGERER: 'UNCOMMON',
    FELIX: 'UNCOMMON', FISHERMAN: 'UNCOMMON', FRIENDLY_HIKER: 'UNCOMMON',
    GEONATHAN_GREATFORGE: 'UNCOMMON', GIMLEY: 'UNCOMMON', GUY: 'UNCOMMON',
    HORNUM: 'UNCOMMON', HUNGRY_HIKER: 'UNCOMMON', JACK: 'UNCOMMON',
    JACOB: 'UNCOMMON', JAMIE: 'UNCOMMON', JOTRAELINE_GREATFORGE: 'UNCOMMON',
    LEO: 'UNCOMMON', LIAM: 'UNCOMMON', LIBRARIAN: 'UNCOMMON',
    LUMBER_JACK: 'UNCOMMON', LYNN: 'UNCOMMON', MASON: 'UNCOMMON',
    ODAWA: 'UNCOMMON', ORINGO: 'UNCOMMON', PEST_WRANGLER: 'UNCOMMON',
    PLUMBER_JOE: 'UNCOMMON', RHYS: 'UNCOMMON', ROYAL_RESIDENT_NEIGHBOR: 'UNCOMMON',
    ROYAL_RESIDENT_SNOOTY: 'UNCOMMON', RYU: 'UNCOMMON', SARGWYN: 'UNCOMMON',
    SHAGGY: 'UNCOMMON', STELLA: 'UNCOMMON', TARWEN: 'UNCOMMON',
    TERRY: 'UNCOMMON', TOM: 'UNCOMMON', TREVOR: 'UNCOMMON',
    VEX: 'UNCOMMON', WEAPONSMITH: 'UNCOMMON', WIZARD: 'UNCOMMON',
    XALX: 'UNCOMMON',
    BARTENDER: 'RARE', DALBREK: 'RARE', EMISSARY_SISKO: 'RARE',
    FRAGILIS: 'RARE', GOLD_FORGER: 'RARE', GRANDMA_WOLF: 'RARE',
    GWENDOLYN: 'RARE', IRON_FORGER: 'RARE', LAZY_MINER: 'RARE',
    LUMINA: 'RARE', OLD_MAN_GARRY: 'RARE', PETE: 'RARE',
    PUZZLER: 'RARE', QUEEN_MISMYLA: 'RARE', ROYAL_RESIDENT: 'RARE',
    RUSTY: 'RARE', SEYMOUR: 'RARE', SHIFTY: 'RARE',
    TAMMY: 'RARE', TIA_THE_FAIRY: 'RARE', VINYL_COLLECTOR: 'RARE',
    ZOG: 'RARE',
    BETH: 'LEGENDARY', BAKER: 'LEGENDARY', CLERK_SERAPHINE: 'LEGENDARY',
    JERRY: 'LEGENDARY', MADAME_ELEANOR_Q_GOLDSWORTH_III: 'LEGENDARY',
    PEST_WRANGLER_DISGUISED: 'LEGENDARY', SIRIUS: 'LEGENDARY',
    MAEVE: 'MYTHIC', RAVENOUS_RHINO: 'MYTHIC',
    SPACEMAN: 'SPECIAL'
};

const VISITOR_GARDEN_LEVEL_REQ_MAP = {
    ADVENTURER: 3, ALCHEMIST: 10, ANDREW: 1,
    ANITA: 2, ARTHUR: 1, BANKER_BROADJAW: 7,
    DUKE: 1, DUSK: 6, EMISSARY_CARLTON: 8,
    EMISSARY_CEANNA: 3, EMISSARY_FRAISER: 6, EMISSARY_WILSON: 2,
    FARMER_JON: 1, FARMHAND: 3, FEAR_MONGERER: 4,
    FELIX: 1, FISHERMAN: 1, FRIENDLY_HIKER: 1,
    GEONATHAN_GREATFORGE: 1, GIMLEY: 1, GUY: 9,
    HORNUM: 1, HUNGRY_HIKER: 1, JACK: 1,
    JACOB: 1, JAMIE: 1, JOTRAELINE_GREATFORGE: 1,
    LEO: 1, LIAM: 1, LIBRARIAN: 5,
    LUMBER_JACK: 9, LYNN: 1, MASON: 1,
    ODAWA: 1, ORINGO: 1, PEST_WRANGLER: 1,
    PLUMBER_JOE: 7, RHYS: 4, ROYAL_RESIDENT_NEIGHBOR: 1,
    ROYAL_RESIDENT_SNOOTY: 1, RYU: 1, SARGWYN: 1,
    SHAGGY: 1, STELLA: 1, TARWEN: 1,
    TERRY: 1, TOM: 1, TREVOR: 1,
    VEX: 1, WEAPONSMITH: 3, WIZARD: 3,
    XALX: 5, BARTENDER: 1, DALBREK: 1,
    EMISSARY_SISKO: 1, FRAGILIS: 7, GOLD_FORGER: 2,
    GRANDMA_WOLF: 1, GWENDOLYN: 1, IRON_FORGER: 2,
    LAZY_MINER: 8, LUMINA: 4, OLD_MAN_GARRY: 8,
    PETE: 7, PUZZLER: 2, QUEEN_MISMYLA: 2,
    ROYAL_RESIDENT: 7, RUSTY: 1, SEYMOUR: 4,
    SHIFTY: 6, TAMMY: 7, TIA_THE_FAIRY: 1,
    VINYL_COLLECTOR: 1, ZOG: 7, BETH: 1,
    BAKER: 1, CLERK_SERAPHINE: 5, JERRY: 1,
    MADAME_ELEANOR_Q_GOLDSWORTH_III: 2, PEST_WRANGLER_DISGUISED: 1, SIRIUS: 1,
    MAEVE: 12, RAVENOUS_RHINO: 1, SPACEMAN: 15
};

const VISITOR_CROP_DESIRE_MAP = {
    ADVENTURER: ['POTATO'], ALCHEMIST: ['NETHER_WART'], ANDREW: ['ANY'],
    ANITA: ['CARROT'], ARTHUR: ['WHEAT'], BANKER_BROADJAW: ['CACTUS'],
    DUKE: ['ANY'], DUSK: ['MELON'], EMISSARY_CARLTON: ['COCOA_BEANS'],
    EMISSARY_CEANNA: ['POTATO'], EMISSARY_FRAISER: ['MELON'], EMISSARY_WILSON: ['CARROT'],
    FARMER_JON: ['SUGAR_CANE'], FARMHAND: ['WHEAT', 'CARROT', 'POTATO'], FEAR_MONGERER: ['PUMPKIN'],
    FELIX: ['ANY'], FISHERMAN: ['CARROT'], FRIENDLY_HIKER: ['MEAT'],
    GEONATHAN_GREATFORGE: ['COMPOST'], GIMLEY: ['WHEAT'], GUY: ['MUSHROOM'],
    HORNUM: ['WHEAT'], HUNGRY_HIKER: ['PUMPKIN'], JACK: ['ANY'],
    JACOB: ['WHEAT'], JAMIE: ['ANY'], JOTRAELINE_GREATFORGE: ['COMPOST'],
    LEO: ['ANY'], LIAM: ['ANY'], LIBRARIAN: ['SUGAR_CANE'],
    LUMBER_JACK: ['CARROT', 'POTATO', 'MELON', 'PUMPKIN', 'MUSHROOM'], LYNN: ['ANY'], MASON: ['MEAT', 'POTATO', 'CARROT', 'MUSHROOM'],
    ODAWA: ['ANY'], ORINGO: ['WHEAT'], PEST_WRANGLER: ['SPECIAL'],
    PLUMBER_JOE: ['CACTUS'], RHYS: ['PUMPKIN'], ROYAL_RESIDENT_NEIGHBOR: ['ANY'],
    ROYAL_RESIDENT_SNOOTY: ['ANY'], RYU: ['ANY'], SARGWYN: ['WHEAT'],
    SHAGGY: ['ANY'], STELLA: ['ANY'], TARWEN: ['WHEAT'],
    TERRY: ['MELON'], TOM: ['ANY'], TREVOR: ['ANY'],
    VEX: ['ANY'], WEAPONSMITH: ['POTATO'], WIZARD: ['POTATO'],
    XALX: ['SUGAR'], BARTENDER: ['ANY_TWO'], DALBREK: ['ANY'],
    EMISSARY_SISKO: ['MUSHROOM'], FRAGILIS: ['CACTUS'], GOLD_FORGER: ['GOLDEN_CARROT'],
    GRANDMA_WOLF: ['ANY_THREE'], GWENDOLYN: ['COCOA_BEANS'], IRON_FORGER: ['CARROT'],
    LAZY_MINER: ['COCOA_BEANS'], LUMINA: ['PUMPKIN'], OLD_MAN_GARRY: ['COCOA_BEANS'],
    PETE: ['SUGAR'], PUZZLER: ['CARROT'], QUEEN_MISMYLA: ['ANY_TWO'],
    ROYAL_RESIDENT: ['SUGAR', 'WHEAT'], RUSTY: ['ANY'], SEYMOUR: ['PUMPKIN'],
    SHIFTY: ['MELON'], TAMMY: ['CACTUS'], TIA_THE_FAIRY: ['ANY'],
    VINYL_COLLECTOR: ['VINYL'], ZOG: ['MELON', 'CACTUS'], BETH: ['ANY'],
    BAKER: ['FLOUR'], CLERK_SERAPHINE: ['SUGAR_CANE'], JERRY: ['ANY'],
    MADAME_ELEANOR_Q_GOLDSWORTH_III: ['GOLDEN_CARROT'], PEST_WRANGLER_DISGUISED: ['SPECIAL'], SIRIUS: ['ANY'],
    MAEVE: ['SPECIAL_CROPS'], RAVENOUS_RHINO: ['CAKE', 'BREAD'], SPACEMAN: ['ANY']
};

const VISITOR_BONUS_REWARD_MAP = {
    ADVENTURER: [], ALCHEMIST: [], ANDREW: [], ANITA: [], ARTHUR: [], BANKER_BROADJAW: [], DUKE: [],
    DUSK: ['Random Rune x1'], EMISSARY_CARLTON: [], EMISSARY_CEANNA: [], EMISSARY_FRAISER: [], EMISSARY_WILSON: [],
    FARMER_JON: [], FARMHAND: [], FEAR_MONGERER: ['Green/Purple Candy x1'], FELIX: [], FISHERMAN: [], FRIENDLY_HIKER: [],
    GEONATHAN_GREATFORGE: ['Biofuel x1'], GIMLEY: [], GUY: [], HORNUM: [], HUNGRY_HIKER: ['Farming Exp Boost x1'],
    JACK: [], JACOB: ["Jacob's Ticket x1"], JAMIE: [], JOTRAELINE_GREATFORGE: ['Biofuel x1'],
    LEO: [], LIAM: [], LIBRARIAN: ['Random Enchanted Book'], LUMBER_JACK: [], LYNN: [], MASON: [], ODAWA: ['Jungle Key x1'],
    ORINGO: ['Pet Cake x1'], PEST_WRANGLER: ['Fine Flour x5'], PLUMBER_JOE: [], RHYS: [], ROYAL_RESIDENT_NEIGHBOR: [],
    ROYAL_RESIDENT_SNOOTY: [], RYU: [], SARGWYN: [], SHAGGY: ['Arachne Fragment x1'], STELLA: [], TARWEN: [], TERRY: [],
    TOM: [], TREVOR: ['2 Pelts'], VEX: ['Dead Bush x1'], WEAPONSMITH: [], WIZARD: [], XALX: ['Mysterious Crop x1'],
    BARTENDER: [], DALBREK: [], EMISSARY_SISKO: [], FRAGILIS: [], GOLD_FORGER: ['2-5 Gold Essence'], GRANDMA_WOLF: [],
    GWENDOLYN: ['Crystal Hollows Pass'], IRON_FORGER: [], LAZY_MINER: [], LUMINA: [], OLD_MAN_GARRY: [], PETE: [], PUZZLER: [],
    QUEEN_MISMYLA: [], ROYAL_RESIDENT: [], RUSTY: ['Iron Hoe x1'], SEYMOUR: ["Seymour's Armor Piece"], SHIFTY: [], TAMMY: [],
    TIA_THE_FAIRY: ['Fairy Soul x1'], VINYL_COLLECTOR: ['Fine Flour x15'], ZOG: [],
    BETH: [], BAKER: [], CLERK_SERAPHINE: [], JERRY: [], MADAME_ELEANOR_Q_GOLDSWORTH_III: [], PEST_WRANGLER_DISGUISED: ['Fine Flour x50'], SIRIUS: [],
    MAEVE: ['Harvest Harbinger Potion x1'], RAVENOUS_RHINO: ['Dedication IV Book x1'], SPACEMAN: ['Space Helmet x1']
};

const GARDEN_PESTS_CONFIG = {
    FLY: { name: 'Fly', api_id_pattern: 'pest_fly', max_tier_kills: 250, ff_per_max_tier: 0.5 },
    CRICKET: { name: 'Cricket', api_id_pattern: 'pest_cricket', max_tier_kills: 250, ff_per_max_tier: 0.5 },
    LOCUST: { name: 'Locust', api_id_pattern: 'pest_locust', max_tier_kills: 250, ff_per_max_tier: 0.5 },
    RAT: { name: 'Rat', api_id_pattern: 'pest_rat', max_tier_kills: 250, ff_per_max_tier: 1.0 },
    MOSQUITO: { name: 'Mosquito', api_id_pattern: 'pest_mosquito', max_tier_kills: 250, ff_per_max_tier: 0.5 },
    EARTHWORM: { name: 'Earthworm', api_id_pattern: 'pest_worm', max_tier_kills: 250, ff_per_max_tier: 0.5 },
    MITE: { name: 'Mite', api_id_pattern: 'pest_mite', max_tier_kills: 250, ff_per_max_tier: 0.5 },
    MOTH: { name: 'Moth', api_id_pattern: 'pest_moth', max_tier_kills: 250, ff_per_max_tier: 0.5 },
    SLUG: { name: 'Slug', api_id_pattern: 'pest_slug', max_tier_kills: 250, ff_per_max_tier: 0.5 },
    BEETLE: { name: 'Beetle', api_id_pattern: 'pest_beetle', max_tier_kills: 250, ff_per_max_tier: 0.5 },
    DRAGONFLY: { name: 'Dragonfly', api_id_pattern: 'pest_dragonfly', max_tier_kills: 250, ff_per_max_tier: 0 },
    FIREFLY: { name: 'Firefly', api_id_pattern: 'pest_firefly', max_tier_kills: 250, ff_per_max_tier: 0 },
    PRAYING_MANTIS: { name: 'Praying Mantis', api_id_pattern: 'pest_praying', max_tier_kills: 250, ff_per_max_tier: 0 },
    FIELD_MOUSE: { name: 'Field Mouse', api_id_pattern: 'pest_mouse', max_tier_kills: 100, ff_per_max_tier: 0 }
};

const GARDEN_MUTATION_OBJECTIVES = ['spread_mutation', 'harvest_mutation'];

module.exports = {
    CROP_IDS_MAP,
    PERSONAL_BEST_FF_AMOUNTS,
    CROP_MILESTONE_CAPS,
    VISITOR_RARITY_MAP,
    VISITOR_GARDEN_LEVEL_REQ_MAP,
    VISITOR_CROP_DESIRE_MAP,
    VISITOR_BONUS_REWARD_MAP,
    GARDEN_PESTS_CONFIG,
    GARDEN_MUTATION_OBJECTIVES
};
