const Logger = require("../../src/Logger");

function getRabbitRarity(rabbit) {
    let rabbit_rarity = rabbits[rabbit];

    if (rabbit_rarity == undefined) {
        Logger.warnMessage(`Found unknown rabbit: ${rabbit}`);
        return 'UNKNOWN';
    }
    return rabbit_rarity;
}

let rabbits = {};

let common_rabbits = [
    'aaron',
    'able',
    'acker',
    'alfie',
    'alice',
    'almond_amaretto',
    'alpha',
    'angus',
    'annabelle',
    'archie',
    'arnie',
    'audi',
    'augustus',
    'baby',
    'badger',
    'bagel',
    'baldwin',
    'baloo',
    'barney',
    'bartholomew',
    'basket',
    'baxter',
    'beatrice',
    'bertha',
    'bibsy',
    'billy',
    'bindi',
    'binky',
    'blake',
    'bob',
    'bramble',
    'breeze',
    'brian',
    'brie',
    'bronson',
    'brooks',
    'bruce',
    'bruno',
    'bud',
    'bugster',
    'bugsy',
    'buttercream_blossom',
    'cadet',
    'callie',
    'cave',
    'chase',
    'chester',
    'chip',
    'chomper',
    'chompsky',
    'claude',
    'cocoa_comet',
    'collin',
    'copper',
    'cottontail',
    'cricket',
    'crush',
    'cuddles',
    'cupcake',
    'delboy',
    'delilah',
    'demi',
    'digger',
    'duchess',
    'dulce_drizzle',
    'dusty',
    'ellie',
    'ember',
    'emerson',
    'espresso_eclair',
    'eta',
    'fergie',
    'fievel',
    'fluffy',
    'francine',
    'frank',
    'frankie',
    'fudge',
    'fuzzy',
    'george',
    'ginger',
    'ginny',
    'gizmo',
    'gloria',
    'gouda',
    'gracie',
    'guinness',
    'gunther',
    'hadley',
    'harley',
    'hefner',
    'heidie',
    'herbie',
    'hershey',
    'hondo',
    'hopper',
    'hubby',
    'huck',
    'hugo',
    'humphrey',
    'hunter',
    'iggy',
    'indie',
    'jade',
    'jake',
    'james',
    'jammer',
    'jasmine',
    'jazmin',
    'jeffery',
    'jerry',
    'joey',
    'jonah',
    'josephine',
    'lenny',
    'lily',
    'lone_ranger',
    'lotte',
    'louie',
    'mandy',
    'marlow',
    'maui',
    'max',
    'mickey',
    'miles',
    'milly',
    'mimi',
    'mochi',
    'molly',
    'mona',
    'moody',
    'mookie',
    'mopsy',
    'morris',
    'natalie',
    'ned',
    'nibbles',
    'niko',
    'niza',
    'nu',
    'nutmeg',
    'oletta',
    'oliver',
    'olivette',
    'olivier',
    'ollie',
    'paddy',
    'patch',
    'pebbles',
    'penny',
    'peony',
    'petunia',
    'pickles',
    'picky',
    'pinky',
    'poppy',
    'porter',
    'quentin',
    'razzie',
    'reginald',
    'remi',
    'ressie',
    'ricky',
    'riley',
    'rolf',
    'rosco',
    'ross',
    'rowdy',
    'ruben',
    'rupert',
    'ryder',
    'sassy',
    'scooter',
    'scotch',
    'scout',
    'scuba',
    'selene',
    'skippe',
    'smokey',
    'sniffles',
    'snoppy',
    'snuffy',
    'sophie',
    'sorbet',
    'spencer',
    'spot',
    'stanley',
    'stinky',
    'stuart',
    'suri',
    'tagalong',
    'tau',
    'teddy',
    'thalai',
    'theo',
    'theodore',
    'thumper',
    'ticky',
    'tobi',
    'webb',
    'william',
    'winston',
    'woody',
    'zack',
    'zea'
];

for (let rabbit of common_rabbits) {
    rabbits[rabbit] = 'COMMON';
}

let uncommon_rabbits = [
    'abi',
    'abigail',
    'alexa',
    'alexander',
    'alpaca',
    'amazon',
    'arachno',
    'ashes',
    'asterix',
    'average',
    'bambam',
    'bandit',
    'barcode',
    'benji',
    'beta',
    'bilbo',
    'blossom',
    'blueberry',
    'brutus',
    'bubbles',
    'buckwheat',
    'buffalo',
    'bugs',
    'bumper',
    'buster',
    'butters',
    'candi',
    'carter',
    'casper',
    'cassidy',
    'charmin',
    'chewy',
    'chilli',
    'chubby',
    'cloudy',
    'cookie',
    'cooper',
    'cotton',
    'cotton_puff',
    'cottonball',
    'dalton',
    'dandelion',
    'darla',
    'dash',
    'demarcus',
    'demetrious',
    'destiny',
    'domino',
    'eastwood',
    'ella',
    'fish',
    'fitch',
    'flip_flop',
    'forrest',
    'fudge_fountain',
    'gadget',
    'gee_gee',
    'ginger_glaze',
    'goofy',
    'harmony',
    'honey_hazelnut',
    'hop_a_long',
    'icing_ivy',
    'inferno',
    'irena',
    'jasmine_jello',
    'jazz',
    'jelly_bean',
    'kobi',
    'leopold',
    'lulu',
    'maybelline',
    'mediocrity',
    'milo',
    'modest',
    'morgan',
    'oakley',
    'obelix',
    'oreo',
    'otto',
    'ozwald',
    'pancake',
    'patches',
    'penelope',
    'pepsi',
    'pillsbury',
    'polka_dot',
    'porsche',
    'prestige',
    'pretzel',
    'prudent',
    'quincy',
    'raven',
    'ringo',
    'rusty',
    'sargent',
    'seinfield',
    'snoopy',
    'sprinkles',
    'squish',
    'stewart',
    'sven',
    'sweetpea',
    'sylvester',
    'theta',
    'toby',
    'trixie',
    'una',
    'upsilon',
    'void',
    'wadsworth',
    'waffle',
    'xi',
    'zombie'
];

for (let rabbit of uncommon_rabbits) {
    rabbits[rabbit] = 'UNCOMMON';
}

let rare_rabbits = [
    'aladdin',
    'aloysius',
    'barbie',
    'bishop',
    'blackberry',
    'blackjack',
    'bugatti',
    'bun_bun',
    'burst',
    'cajun',
    'caramel',
    'casanova',
    'chevy',
    'cinnamon',
    'crystal',
    'dallas',
    'draco',
    'easter',
    'elvis',
    'favor',
    'figaro',
    'frodo',
    'gamma',
    'gremlin',
    'honey',
    'hope',
    'hyde',
    'iota',
    'jasper',
    'jynx',
    'kiwi_kiss',
    'lavender_lemon',
    'linus',
    'maple_mirage',
    'midnight',
    'monalisa',
    'murphy',
    'neptune',
    'nougat_nebula',
    'olympe',
    'omicron',
    'onyx',
    'orange_obsidian',
    'orlando',
    'paddington',
    'peanut',
    'pepper',
    'phantom',
    'phi',
    'popcorn',
    'pride',
    'pumpkin',
    'river',
    'sage',
    'snowball',
    'spirit',
    'spooky',
    'stormy',
    'sunny',
    'tornado',
    'tricky',
    'uncle_buck',
    'vlad',
    'wesson',
    'widget',
    'willow',
    'zero'
];

for (let rabbit of rare_rabbits) {
    rabbits[rabbit] = 'RARE';
}

let epic_rabbits = [
    'ace',
    'achilles',
    'alpine',
    'angel',
    'calypso',
    'chi',
    'comet',
    'delta',
    'gatsby',
    'implode',
    'jedi',
    'kappa',
    'ken',
    'kiera',
    'kodo',
    'merlin',
    'necron',
    'peppermint_pearl',
    'pi',
    'prince',
    'punch',
    'quince_quark',
    'rambo',
    'raspberry_ripple',
    'saga',
    'simba',
    'strawberry_swirl',
    'thor',
    'toffee_tulip',
    'trix',
    'turbo'
];

for (let rabbit of epic_rabbits) {
    rabbits[rabbit] = 'EPIC';
}

let legendary_rabbits = [
    'apollo',
    'april',
    'atlas',
    'echo',
    'el_dorado',
    'epsilon',
    'extra',
    'general',
    'houdini',
    'kaeman',
    'lambda',
    'magic',
    'mystic',
    'nova',
    'psi',
    'rho',
    'shadow',
    'solomon',
    'storm',
    'ube_unicorn',
    'vanilla_vortex',
    'walnut_whirl',
    'xoco_xanudu',
    'yogurt_yucca'
];

for (let rabbit of legendary_rabbits) {
    rabbits[rabbit] = 'LEGENDARY';
}

let mythic_rabbits = [
    'dante',
    'einstein',
    'galaxy',
    'king',
    'mu',
    'napoleon',
    'omega',
    'sigma',
    'zest_zephyr',
    'zeta',
    'zorro'
];

for (let rabbit of mythic_rabbits) {
    rabbits[rabbit] = 'MYTHIC';
}

let divine_rabbits = ['aurora', 'celestia', 'orion', 'starfire', 'vega'];

for (let rabbit of divine_rabbits) {
    rabbits[rabbit] = 'DIVINE';
}

module.exports = {
    getRabbitRarity: getRabbitRarity,
    rabbits: rabbits,
    common: common_rabbits,
    uncommon: uncommon_rabbits,
    rare: rare_rabbits,
    epic: epic_rabbits,
    legendary: legendary_rabbits,
    mythic: mythic_rabbits,
    divine: divine_rabbits
};
